title: Luke Fender
email: lfender6445@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  development adventures
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://lfender6445.github.io" # the base hostname & protocol for your site
twitter_username: lfender6445
github_username:  lfender6445

# Build settings
markdown: kramdown
