title: Luke Fender
email: lfender6445@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog about everything and nothing
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: lfender6445
github_username:  lfender6445

# Build settings
markdown: kramdown
